"""
200 HR Analytics JSON Examples for Huntflow Integration
Comprehensive collection of realistic queries using systematic metrics and real data patterns.
"""

# Real data context for examples
REAL_RECRUITERS = ["Анастасия Богач", "Михаил Танский", "Виталий Глибин", "Алина Петрова", "София Данилова"]
REAL_STATUSES = ["Новые", "Интервью", "Резюме у заказчика", "Отправлено письмо", "Оффер принят", "Отказ"]
REAL_POSITIONS = ["Python Developer", "Java Developer", "QA Engineer", "Designer", "Sales Manager", "HR Manager"]

# 200 HR Analytics Examples organized by categories
HR_ANALYTICS_EXAMPLES = [

# ==========================================
# CATEGORY 1: BASIC COUNTS (1-25)
# ==========================================

{"query": "сколько всего кандидатов в системе?", "json": {"report_title": "Total Applicants", "main_metric": {"label": "Total Applicants", "value": {"operation": "count", "entity": "applicants_all"}}}},
{"query": "сколько открытых вакансий?", "json": {"report_title": "Open Vacancies", "main_metric": {"label": "Open Vacancies", "value": {"operation": "count", "entity": "vacancies_open"}}}},
{"query": "количество активных кандидатов в воронке", "json": {"report_title": "Active Pipeline Candidates", "main_metric": {"label": "Active Candidates", "value": {"operation": "count", "entity": "applicants_by_status"}}}},
{"query": "общее количество рекрутеров", "json": {"report_title": "Total Recruiters", "main_metric": {"label": "Total Recruiters", "value": {"operation": "count", "entity": "recruiters_all"}}}},
{"query": "сколько статусов в системе?", "json": {"report_title": "Total Statuses", "main_metric": {"label": "Total Statuses", "value": {"operation": "count", "entity": "statuses_all"}}}},
{"query": "количество закрытых вакансий", "json": {"report_title": "Closed Vacancies", "main_metric": {"label": "Closed Vacancies", "value": {"operation": "count", "entity": "vacancies_closed"}}}},
{"query": "сколько нанятых кандидатов?", "json": {"report_title": "Hired Candidates", "main_metric": {"label": "Hired Candidates", "value": {"operation": "count", "entity": "applicants_hired"}}}},
{"query": "количество групп статусов", "json": {"report_title": "Status Groups", "main_metric": {"label": "Status Groups Count", "value": {"operation": "count", "entity": "status_groups"}}}},
{"query": "сколько всего вакансий в системе?", "json": {"report_title": "All Vacancies", "main_metric": {"label": "Total Vacancies", "value": {"operation": "count", "entity": "vacancies_all"}}}},
{"query": "количество активных статусов воронки", "json": {"report_title": "Active Pipeline Statuses", "main_metric": {"label": "Active Statuses", "value": {"operation": "count", "entity": "statuses_active"}}}},
{"query": "общее количество источников", "json": {"report_title": "Total Sources", "main_metric": {"label": "Total Sources", "value": {"operation": "count", "entity": "sources_all"}}}},
{"query": "сколько менеджеров по найму?", "json": {"report_title": "Hiring Managers", "main_metric": {"label": "Hiring Managers", "value": {"operation": "count", "entity": "hiring_managers_all"}}}},
{"query": "количество отделов", "json": {"report_title": "Total Divisions", "main_metric": {"label": "Total Divisions", "value": {"operation": "count", "entity": "divisions_all"}}}},
{"query": "сколько причин отказов?", "json": {"report_title": "Rejection Reasons", "main_metric": {"label": "Rejection Reasons", "value": {"operation": "count", "entity": "rejection_reasons_all"}}}},
{"query": "общее количество тегов", "json": {"report_title": "Total Tags", "main_metric": {"label": "Total Tags", "value": {"operation": "count", "entity": "tags_all"}}}},
{"query": "количество регионов", "json": {"report_title": "Total Regions", "main_metric": {"label": "Total Regions", "value": {"operation": "count", "entity": "regions_all"}}}},
{"query": "сколько вакансий на паузе?", "json": {"report_title": "On Hold Vacancies", "main_metric": {"label": "On Hold Vacancies", "value": {"operation": "count", "entity": "vacancies_all", "filter": {"field": "state", "op": "eq", "value": "HOLD"}}}}},
{"query": "количество архивных вакансий", "json": {"report_title": "Archived Vacancies", "main_metric": {"label": "Archived Vacancies", "value": {"operation": "count", "entity": "vacancies_all", "filter": {"field": "state", "op": "eq", "value": "ARCHIVED"}}}}},
{"query": "сколько кандидатов отклонено?", "json": {"report_title": "Rejected Candidates", "main_metric": {"label": "Rejected Candidates", "value": {"operation": "count", "entity": "applicants_by_status", "filter": {"field": "status_type", "op": "eq", "value": "trash"}}}}},
{"query": "общее количество резюме", "json": {"report_title": "Total Resumes", "main_metric": {"label": "Total Resumes", "value": {"operation": "count", "entity": "resumes_all"}}}},
{"query": "количество высокоприоритетных вакансий", "json": {"report_title": "High Priority Vacancies", "main_metric": {"label": "High Priority", "value": {"operation": "count", "entity": "vacancies_all", "filter": {"field": "priority", "op": "eq", "value": "high"}}}}},
{"query": "сколько кандидатов в статусе Оффер?", "json": {"report_title": "Offer Stage Candidates", "main_metric": {"label": "Offer Candidates", "value": {"operation": "count", "entity": "applicants_by_status", "filter": {"field": "status_name", "op": "icontains", "value": "Оффер"}}}}},
{"query": "количество действий в системе", "json": {"report_title": "Total System Actions", "main_metric": {"label": "Total Actions", "value": {"operation": "sum", "entity": "actions_by_recruiter"}}}},
{"query": "общее количество переходов по воронке", "json": {"report_title": "Total Pipeline Moves", "main_metric": {"label": "Total Moves", "value": {"operation": "sum", "entity": "moves_by_recruiter"}}}},
{"query": "сколько кандидатов добавлено рекрутерами?", "json": {"report_title": "Added Candidates", "main_metric": {"label": "Added Candidates", "value": {"operation": "sum", "entity": "applicants_added_by_recruiter"}}}},

# ==========================================
# CATEGORY 2: TIME-BASED QUERIES (26-50)
# ==========================================

{"query": "вакансии созданные за последний месяц", "json": {"report_title": "Vacancies Created Last Month", "main_metric": {"label": "New Vacancies (30 days)", "value": {"operation": "count", "entity": "vacancies_all", "filter": {"field": "created", "op": "gte", "value": "2025-05-19T00:00:00"}}}}},
{"query": "кандидаты добавленные за последние 90 дней", "json": {"report_title": "Recent Applicants (90 days)", "main_metric": {"label": "Recent Applicants", "value": {"operation": "count", "entity": "applicants_all", "filter": {"field": "created", "op": "gte", "value": "2025-03-20T00:00:00"}}}}},
{"query": "активность за текущий год", "json": {"report_title": "This Year Activity", "main_metric": {"label": "Actions This Year", "value": {"operation": "sum", "entity": "actions_by_recruiter", "filter": {"field": "created", "op": "gte", "value": "2024-06-18T00:00:00"}}}}},
{"query": "вакансии созданные за последние 6 месяцев", "json": {"report_title": "Vacancies Last 6 Months", "main_metric": {"label": "Vacancies (6mo)", "value": {"operation": "count", "entity": "vacancies_all", "filter": {"field": "created", "op": "gte", "value": "2024-12-20T00:00:00"}}}}},
{"query": "найм за последний год", "json": {"report_title": "Hires Last Year", "main_metric": {"label": "Yearly Hires", "value": {"operation": "count", "entity": "applicants_hired", "filter": {"field": "created", "op": "gte", "value": "2024-06-18T00:00:00"}}}}},
{"query": "открытые вакансии созданные в этом квартале", "json": {"report_title": "Open Vacancies This Quarter", "main_metric": {"label": "New Open Vacancies", "value": {"operation": "count", "entity": "vacancies_all", "filter": [{"field": "state", "op": "eq", "value": "OPEN"}, {"field": "created", "op": "gte", "value": "2025-03-20T00:00:00"}]}}}},
{"query": "недавняя активность рекрутеров (30 дней)", "json": {"report_title": "Recent Recruiter Activity", "main_metric": {"label": "Recent Actions", "value": {"operation": "sum", "entity": "actions_by_recruiter", "filter": {"field": "created", "op": "gte", "value": "2025-05-19T00:00:00"}}}}},
{"query": "движения по воронке за последние 2 недели", "json": {"report_title": "Recent Pipeline Moves", "main_metric": {"label": "Recent Moves", "value": {"operation": "sum", "entity": "moves_by_recruiter", "filter": {"field": "created", "op": "gte", "value": "2025-06-04T00:00:00"}}}}},
{"query": "кандидаты добавленные сегодня", "json": {"report_title": "Today's New Candidates", "main_metric": {"label": "Today's Applicants", "value": {"operation": "count", "entity": "applicants_all", "filter": {"field": "created", "op": "gte", "value": "2025-06-18T00:00:00"}}}}},
{"query": "закрытые вакансии за прошлую неделю", "json": {"report_title": "Last Week Closed Vacancies", "main_metric": {"label": "Last Week Closed", "value": {"operation": "count", "entity": "vacancies_all", "filter": [{"field": "state", "op": "eq", "value": "CLOSED"}, {"field": "updated", "op": "gte", "value": "2025-06-11T00:00:00"}]}}}},
{"query": "найм за этот месяц", "json": {"report_title": "This Month Hires", "main_metric": {"label": "Monthly Hires", "value": {"operation": "count", "entity": "applicants_hired", "filter": {"field": "hired_date", "op": "gte", "value": "2025-06-01T00:00:00"}}}}},
{"query": "вакансии обновленные за последние 7 дней", "json": {"report_title": "Recently Updated Vacancies", "main_metric": {"label": "Updated Vacancies", "value": {"operation": "count", "entity": "vacancies_all", "filter": {"field": "updated", "op": "gte", "value": "2025-06-11T00:00:00"}}}}},
{"query": "отказы за текущий квартал", "json": {"report_title": "This Quarter Rejections", "main_metric": {"label": "Quarterly Rejections", "value": {"operation": "sum", "entity": "rejections_by_recruiter", "filter": {"field": "created", "op": "gte", "value": "2025-03-20T00:00:00"}}}}},
{"query": "кандидаты из LinkedIn за месяц", "json": {"report_title": "LinkedIn Candidates This Month", "main_metric": {"label": "LinkedIn Monthly", "value": {"operation": "count", "entity": "applicants_by_source", "filter": [{"field": "source_name", "op": "eq", "value": "LinkedIn"}, {"field": "created", "op": "gte", "value": "2025-05-19T00:00:00"}]}}}},
{"query": "активность в воронке за вчера", "json": {"report_title": "Yesterday Pipeline Activity", "main_metric": {"label": "Yesterday Activity", "value": {"operation": "sum", "entity": "moves_by_recruiter", "filter": {"field": "created", "op": "gte", "value": "2025-06-17T00:00:00"}}}}},
{"query": "новые резюме за неделю", "json": {"report_title": "New Resumes This Week", "main_metric": {"label": "Weekly Resumes", "value": {"operation": "count", "entity": "resumes_all", "filter": {"field": "created", "op": "gte", "value": "2025-06-11T00:00:00"}}}}},
{"query": "вакансии в работе более 3 месяцев", "json": {"report_title": "Long Running Vacancies", "main_metric": {"label": "Long Running", "value": {"operation": "count", "entity": "vacancies_open", "filter": {"field": "created", "op": "lt", "value": "2025-03-20T00:00:00"}}}}},
{"query": "быстрые закрытия (менее месяца)", "json": {"report_title": "Fast Closures", "main_metric": {"label": "Fast Closed", "value": {"operation": "count", "entity": "vacancies_closed", "filter": {"field": "days_to_close", "op": "lt", "value": 30}}}}},
{"query": "сезонные тренды найма", "json": {"report_title": "Seasonal Hiring Trends", "main_metric": {"label": "Seasonal Hires", "value": {"operation": "count", "entity": "applicants_hired"}, "chart": {"graph_description": "Hiring volume by month", "chart_type": "line", "x_axis_name": "Month", "y_axis_name": "Hires", "x_axis": {"operation": "date_trunc", "field": "hired_date"}, "y_axis": {"operation": "count", "entity": "applicants_hired", "group_by": {"field": "hired_date"}}}}}},
{"query": "пиковые периоды подачи заявок", "json": {"report_title": "Peak Application Periods", "main_metric": {"label": "Peak Applications", "value": {"operation": "count", "entity": "applicants_all"}, "chart": {"graph_description": "Application volume by day of week", "chart_type": "bar", "x_axis_name": "Day", "y_axis_name": "Applications", "x_axis": {"operation": "date_trunc", "field": "created"}, "y_axis": {"operation": "count", "entity": "applicants_all", "group_by": {"field": "created"}}}}}},
{"query": "время до первого отклика", "json": {"report_title": "Time to First Response", "main_metric": {"label": "Avg Response Time", "value": {"operation": "avg", "entity": "response_times"}}}},
{"query": "активность по дням недели", "json": {"report_title": "Weekday Activity", "main_metric": {"label": "Daily Activity", "value": {"operation": "avg", "entity": "actions_by_recruiter"}, "chart": {"graph_description": "Activity by day of week", "chart_type": "bar", "x_axis_name": "Day", "y_axis_name": "Actions", "x_axis": {"operation": "date_trunc", "field": "created"}, "y_axis": {"operation": "sum", "entity": "actions_by_recruiter", "group_by": {"field": "day_of_week"}}}}}},
{"query": "ночные vs дневные заявки", "json": {"report_title": "Night vs Day Applications", "main_metric": {"label": "Time Distribution", "value": {"operation": "count", "entity": "applicants_all"}, "chart": {"graph_description": "Applications by time of day", "chart_type": "pie", "x_axis_name": "Time Period", "y_axis_name": "Count", "x_axis": {"operation": "field", "field": "time_period"}, "y_axis": {"operation": "count", "entity": "applicants_all", "group_by": {"field": "hour_of_day"}}}}}},
{"query": "выходные vs будни активность", "json": {"report_title": "Weekend vs Weekday Activity", "main_metric": {"label": "Weekend Activity", "value": {"operation": "sum", "entity": "actions_by_recruiter", "filter": {"field": "is_weekend", "op": "eq", "value": True}}}}},
{"query": "ретроспектива за 12 месяцев", "json": {"report_title": "12 Month Retrospective", "main_metric": {"label": "Year Overview", "value": {"operation": "count", "entity": "applicants_all", "filter": {"field": "created", "op": "gte", "value": "2024-06-18T00:00:00"}}, "chart": {"graph_description": "Monthly trends over the year", "chart_type": "line", "x_axis_name": "Month", "y_axis_name": "Count", "x_axis": {"operation": "date_trunc", "field": "created"}, "y_axis": {"operation": "count", "entity": "applicants_all", "group_by": {"field": "month"}}}}}},

# ==========================================
# CATEGORY 3: RECRUITER PERFORMANCE (51-80)
# ==========================================

{"query": "активность Анастасии Богач", "json": {"report_title": "Анастасия Богач Performance", "main_metric": {"label": "Total Actions", "value": {"operation": "sum", "entity": "actions_by_recruiter", "filter": {"field": "recruiter_name", "op": "eq", "value": "Анастасия Богач"}}}}},
{"query": "кандидаты под управлением Михаила Танского", "json": {"report_title": "Михаил Танский Candidates", "main_metric": {"label": "Managed Candidates", "value": {"operation": "count", "entity": "applicants_by_recruiter", "filter": {"field": "recruiter_name", "op": "eq", "value": "Михаил Танский"}}}}},
{"query": "движения по воронке от Виталия Глибина", "json": {"report_title": "Виталий Глибин Pipeline Moves", "main_metric": {"label": "Pipeline Moves", "value": {"operation": "sum", "entity": "moves_by_recruiter", "filter": {"field": "recruiter_name", "op": "eq", "value": "Виталий Глибин"}}}}},
{"query": "отказы по рекрутерам", "json": {"report_title": "Rejections by Recruiter", "main_metric": {"label": "Total Rejections", "value": {"operation": "sum", "entity": "rejections_by_recruiter"}}, "chart": {"graph_description": "Rejection distribution across recruiters", "chart_type": "bar", "x_axis_name": "Recruiter", "y_axis_name": "Rejections", "x_axis": {"operation": "field", "field": "recruiter_name"}, "y_axis": {"operation": "count", "entity": "rejections_by_recruiter", "group_by": {"field": "recruiter_name"}}}}},
{"query": "топ рекрутеров по найму", "json": {"report_title": "Top Recruiters by Hiring", "main_metric": {"label": "Best Performer", "value": {"operation": "max", "entity": "recruiters_by_hirings"}}, "chart": {"graph_description": "Recruiters ranked by hiring success", "chart_type": "bar", "x_axis_name": "Recruiter", "y_axis_name": "Hirings", "x_axis": {"operation": "field", "field": "recruiter_name"}, "y_axis": {"operation": "count", "entity": "recruiters_by_hirings", "group_by": {"field": "recruiter_name"}}}}},
{"query": "добавленные кандидаты по рекрутерам", "json": {"report_title": "Candidates Added by Recruiter", "main_metric": {"label": "Total Added", "value": {"operation": "sum", "entity": "applicants_added_by_recruiter"}}, "chart": {"graph_description": "New candidates added by each recruiter", "chart_type": "bar", "x_axis_name": "Recruiter", "y_axis_name": "Candidates Added", "x_axis": {"operation": "field", "field": "recruiter_name"}, "y_axis": {"operation": "count", "entity": "applicants_added_by_recruiter", "group_by": {"field": "recruiter_name"}}}}},
{"query": "активность Алины Петровой за месяц", "json": {"report_title": "Алина Петрова Monthly Activity", "main_metric": {"label": "Monthly Actions", "value": {"operation": "sum", "entity": "actions_by_recruiter", "filter": [{"field": "recruiter_name", "op": "eq", "value": "Алина Петрова"}, {"field": "created", "op": "gte", "value": "2025-05-19T00:00:00"}]}}}},
{"query": "эффективность Софии Даниловой", "json": {"report_title": "София Данилова Efficiency", "main_metric": {"label": "Efficiency Score", "value": {"operation": "avg", "entity": "recruiter_efficiency", "filter": {"field": "recruiter_name", "op": "eq", "value": "София Данилова"}}}}},
{"query": "загруженность рекрутеров", "json": {"report_title": "Recruiter Workload", "main_metric": {"label": "Average Workload", "value": {"operation": "avg", "entity": "applicants_by_recruiter"}}, "chart": {"graph_description": "Current candidate load per recruiter", "chart_type": "bar", "x_axis_name": "Recruiter", "y_axis_name": "Active Candidates", "x_axis": {"operation": "field", "field": "recruiter_name"}, "y_axis": {"operation": "count", "entity": "applicants_by_recruiter", "group_by": {"field": "recruiter_name"}}}}},
{"query": "время ответа рекрутеров", "json": {"report_title": "Recruiter Response Time", "main_metric": {"label": "Average Response Time", "value": {"operation": "avg", "entity": "response_times_by_recruiter"}}, "chart": {"graph_description": "Average response time by recruiter", "chart_type": "bar", "x_axis_name": "Recruiter", "y_axis_name": "Hours", "x_axis": {"operation": "field", "field": "recruiter_name"}, "y_axis": {"operation": "avg", "entity": "response_times_by_recruiter", "group_by": {"field": "recruiter_name"}}}}},
{"query": "конверсия рекрутеров в найм", "json": {"report_title": "Recruiter Hire Conversion", "main_metric": {"label": "Conversion Rate", "value": {"operation": "avg", "entity": "recruiter_conversion_rates"}}, "chart": {"graph_description": "Hire conversion rate by recruiter", "chart_type": "bar", "x_axis_name": "Recruiter", "y_axis_name": "Conversion %", "x_axis": {"operation": "field", "field": "recruiter_name"}, "y_axis": {"operation": "avg", "entity": "recruiter_conversion_rates", "group_by": {"field": "recruiter_name"}}}}},
{"query": "качество источников по рекрутерам", "json": {"report_title": "Source Quality by Recruiter", "main_metric": {"label": "Source Quality", "value": {"operation": "avg", "entity": "source_quality_by_recruiter"}}}},
{"query": "скорость закрытия вакансий", "json": {"report_title": "Vacancy Closure Speed", "main_metric": {"label": "Average Days to Close", "value": {"operation": "avg", "entity": "closure_speed_by_recruiter"}}, "chart": {"graph_description": "Days to close vacancy by recruiter", "chart_type": "bar", "x_axis_name": "Recruiter", "y_axis_name": "Days", "x_axis": {"operation": "field", "field": "recruiter_name"}, "y_axis": {"operation": "avg", "entity": "closure_speed_by_recruiter", "group_by": {"field": "recruiter_name"}}}}},
{"query": "новички vs опытные рекрутеры", "json": {"report_title": "Junior vs Senior Recruiters", "main_metric": {"label": "Performance Gap", "value": {"operation": "avg", "entity": "recruiter_experience_performance"}}, "chart": {"graph_description": "Performance by experience level", "chart_type": "bar", "x_axis_name": "Experience Level", "y_axis_name": "Performance Score", "x_axis": {"operation": "field", "field": "experience_level"}, "y_axis": {"operation": "avg", "entity": "recruiter_experience_performance", "group_by": {"field": "experience_level"}}}}},
{"query": "специализация рекрутеров", "json": {"report_title": "Recruiter Specialization", "main_metric": {"label": "Specialization Index", "value": {"operation": "avg", "entity": "recruiter_specialization"}}, "chart": {"graph_description": "Recruiter focus areas", "chart_type": "pie", "x_axis_name": "Specialization", "y_axis_name": "Recruiters", "x_axis": {"operation": "field", "field": "specialization"}, "y_axis": {"operation": "count", "entity": "recruiter_specialization", "group_by": {"field": "specialization"}}}}},
{"query": "командная vs индивидуальная работа", "json": {"report_title": "Team vs Individual Performance", "main_metric": {"label": "Team Performance", "value": {"operation": "avg", "entity": "team_performance_metrics"}}}},
{"query": "рабочая нагрузка vs результаты", "json": {"report_title": "Workload vs Results", "main_metric": {"label": "Efficiency Ratio", "value": {"operation": "avg", "entity": "workload_efficiency"}}, "chart": {"graph_description": "Workload vs hiring success", "chart_type": "scatter", "x_axis_name": "Workload", "y_axis_name": "Hires", "x_axis": {"operation": "field", "field": "workload"}, "y_axis": {"operation": "count", "entity": "recruiter_hires", "group_by": {"field": "recruiter_name"}}}}},
{"query": "топ действий рекрутеров", "json": {"report_title": "Top Recruiter Actions", "main_metric": {"label": "Most Active", "value": {"operation": "max", "entity": "actions_by_recruiter"}}, "chart": {"graph_description": "Most common recruiter actions", "chart_type": "bar", "x_axis_name": "Action Type", "y_axis_name": "Count", "x_axis": {"operation": "field", "field": "action_type"}, "y_axis": {"operation": "count", "entity": "action_types", "group_by": {"field": "action_type"}}}}},
{"query": "равномерность распределения работы", "json": {"report_title": "Work Distribution Balance", "main_metric": {"label": "Distribution Index", "value": {"operation": "avg", "entity": "work_distribution_balance"}}}},
{"query": "сравнение производительности команд", "json": {"report_title": "Team Performance Comparison", "main_metric": {"label": "Team Score", "value": {"operation": "avg", "entity": "team_performance"}}, "chart": {"graph_description": "Performance by team", "chart_type": "bar", "x_axis_name": "Team", "y_axis_name": "Score", "x_axis": {"operation": "field", "field": "team_name"}, "y_axis": {"operation": "avg", "entity": "team_performance", "group_by": {"field": "team_name"}}}}},
{"query": "тренды производительности", "json": {"report_title": "Performance Trends", "main_metric": {"label": "Trend Direction", "value": {"operation": "avg", "entity": "performance_trends"}}, "chart": {"graph_description": "Performance over time", "chart_type": "line", "x_axis_name": "Month", "y_axis_name": "Performance", "x_axis": {"operation": "date_trunc", "field": "created"}, "y_axis": {"operation": "avg", "entity": "performance_trends", "group_by": {"field": "month"}}}}},
{"query": "бенчмарки vs факт", "json": {"report_title": "Benchmarks vs Actual", "main_metric": {"label": "Benchmark Gap", "value": {"operation": "avg", "entity": "benchmark_performance"}}}},
{"query": "обучение vs результаты", "json": {"report_title": "Training Impact", "main_metric": {"label": "Training ROI", "value": {"operation": "avg", "entity": "training_impact"}}}},
{"query": "мотивация команды", "json": {"report_title": "Team Motivation", "main_metric": {"label": "Motivation Index", "value": {"operation": "avg", "entity": "team_motivation"}}}},
{"query": "потенциал роста рекрутеров", "json": {"report_title": "Growth Potential", "main_metric": {"label": "Growth Score", "value": {"operation": "avg", "entity": "growth_potential"}}, "chart": {"graph_description": "Growth potential by recruiter", "chart_type": "bar", "x_axis_name": "Recruiter", "y_axis_name": "Potential Score", "x_axis": {"operation": "field", "field": "recruiter_name"}, "y_axis": {"operation": "avg", "entity": "growth_potential", "group_by": {"field": "recruiter_name"}}}}},
{"query": "выгорание vs продуктивность", "json": {"report_title": "Burnout vs Productivity", "main_metric": {"label": "Burnout Risk", "value": {"operation": "avg", "entity": "burnout_risk"}}}},
{"query": "инновации в процессах", "json": {"report_title": "Process Innovation", "main_metric": {"label": "Innovation Index", "value": {"operation": "avg", "entity": "process_innovation"}}}},
{"query": "адаптация новых рекрутеров", "json": {"report_title": "New Recruiter Adaptation", "main_metric": {"label": "Adaptation Speed", "value": {"operation": "avg", "entity": "adaptation_metrics"}}}},
{"query": "ментор vs подопечный результаты", "json": {"report_title": "Mentor vs Mentee Results", "main_metric": {"label": "Mentoring Impact", "value": {"operation": "avg", "entity": "mentoring_impact"}}}},
{"query": "удаленная vs офисная работа", "json": {"report_title": "Remote vs Office Performance", "main_metric": {"label": "Location Impact", "value": {"operation": "avg", "entity": "location_performance"}}}},

# ==========================================
# CATEGORY 4: CONVERSION METRICS (81-110)
# ==========================================

{"query": "конверсия вакансий в найм", "json": {"report_title": "Vacancy Conversion Rates", "main_metric": {"label": "Average Conversion", "value": {"operation": "avg", "entity": "vacancy_conversion_rates"}}, "chart": {"graph_description": "Conversion rates by vacancy", "chart_type": "bar", "x_axis_name": "Vacancy", "y_axis_name": "Conversion Rate (%)", "x_axis": {"operation": "field", "field": "vacancy_title"}, "y_axis": {"operation": "count", "entity": "vacancy_conversion_rates", "group_by": {"field": "vacancy_title"}}}}},
{"query": "лучшие вакансии по конверсии", "json": {"report_title": "Top Converting Vacancies", "main_metric": {"label": "Best Conversion Rate", "value": {"operation": "max", "entity": "vacancy_conversion_summary"}}, "chart": {"graph_description": "Top 10 vacancies by conversion rate", "chart_type": "bar", "x_axis_name": "Vacancy", "y_axis_name": "Conversion Rate (%)", "x_axis": {"operation": "field", "field": "vacancy_title"}, "y_axis": {"operation": "count", "entity": "vacancy_conversion_summary", "group_by": {"field": "vacancy_title"}}}}},
{"query": "конверсия по статусам вакансий", "json": {"report_title": "Conversion by Vacancy Status", "main_metric": {"label": "Average Conversion", "value": {"operation": "avg", "entity": "vacancy_conversion_by_status"}}, "chart": {"graph_description": "Conversion rates grouped by vacancy status", "chart_type": "bar", "x_axis_name": "Vacancy Status", "y_axis_name": "Average Conversion (%)", "x_axis": {"operation": "field", "field": "vacancy_status"}, "y_axis": {"operation": "count", "entity": "vacancy_conversion_by_status", "group_by": {"field": "vacancy_status"}}}}},
{"query": "общая эффективность найма", "json": {"report_title": "Overall Hiring Efficiency", "main_metric": {"label": "System Conversion Rate", "value": {"operation": "avg", "entity": "vacancy_conversion_summary"}}}},
{"query": "худшие вакансии по конверсии", "json": {"report_title": "Worst Converting Vacancies", "main_metric": {"label": "Lowest Conversion", "value": {"operation": "min", "entity": "vacancy_conversion_rates"}}}},
{"query": "конверсия по источникам", "json": {"report_title": "Source Conversion Rates", "main_metric": {"label": "Source Conversion", "value": {"operation": "avg", "entity": "source_conversion_rates"}}, "chart": {"graph_description": "Conversion rates by candidate source", "chart_type": "bar", "x_axis_name": "Source", "y_axis_name": "Conversion %", "x_axis": {"operation": "field", "field": "source_name"}, "y_axis": {"operation": "avg", "entity": "source_conversion_rates", "group_by": {"field": "source_name"}}}}},
{"query": "конверсия по позициям", "json": {"report_title": "Position Conversion Rates", "main_metric": {"label": "Position Conversion", "value": {"operation": "avg", "entity": "position_conversion_rates"}}, "chart": {"graph_description": "Conversion rates by job position", "chart_type": "bar", "x_axis_name": "Position", "y_axis_name": "Conversion %", "x_axis": {"operation": "field", "field": "position_name"}, "y_axis": {"operation": "avg", "entity": "position_conversion_rates", "group_by": {"field": "position_name"}}}}},
{"query": "конверсия воронки по этапам", "json": {"report_title": "Funnel Stage Conversion", "main_metric": {"label": "Stage Conversion", "value": {"operation": "avg", "entity": "stage_conversion_rates"}}, "chart": {"graph_description": "Conversion between funnel stages", "chart_type": "line", "x_axis_name": "Stage", "y_axis_name": "Conversion %", "x_axis": {"operation": "field", "field": "stage_name"}, "y_axis": {"operation": "avg", "entity": "stage_conversion_rates", "group_by": {"field": "stage_name"}}}}},
{"query": "скорость конверсии", "json": {"report_title": "Conversion Speed", "main_metric": {"label": "Days to Convert", "value": {"operation": "avg", "entity": "conversion_speed"}}}},
{"query": "сезонная конверсия", "json": {"report_title": "Seasonal Conversion", "main_metric": {"label": "Seasonal Rates", "value": {"operation": "avg", "entity": "seasonal_conversion"}}, "chart": {"graph_description": "Conversion rates by season", "chart_type": "line", "x_axis_name": "Month", "y_axis_name": "Conversion %", "x_axis": {"operation": "date_trunc", "field": "created"}, "y_axis": {"operation": "avg", "entity": "seasonal_conversion", "group_by": {"field": "month"}}}}},
{"query": "конверсия приоритетных вакансий", "json": {"report_title": "Priority Vacancy Conversion", "main_metric": {"label": "Priority Conversion", "value": {"operation": "avg", "entity": "vacancy_conversion_rates", "filter": {"field": "priority", "op": "eq", "value": "high"}}}}},
{"query": "географическая конверсия", "json": {"report_title": "Geographic Conversion", "main_metric": {"label": "Regional Conversion", "value": {"operation": "avg", "entity": "geographic_conversion"}}, "chart": {"graph_description": "Conversion rates by region", "chart_type": "bar", "x_axis_name": "Region", "y_axis_name": "Conversion %", "x_axis": {"operation": "field", "field": "region_name"}, "y_axis": {"operation": "avg", "entity": "geographic_conversion", "group_by": {"field": "region_name"}}}}},
{"query": "конверсия по возрасту вакансий", "json": {"report_title": "Vacancy Age Conversion", "main_metric": {"label": "Age Impact", "value": {"operation": "avg", "entity": "vacancy_age_conversion"}}}},
{"query": "конверсия активных vs неактивных", "json": {"report_title": "Active vs Inactive Conversion", "main_metric": {"label": "Activity Impact", "value": {"operation": "avg", "entity": "activity_conversion"}}}},
{"query": "первичная vs повторная конверсия", "json": {"report_title": "First vs Repeat Conversion", "main_metric": {"label": "Repeat Rate", "value": {"operation": "avg", "entity": "repeat_conversion"}}}},
{"query": "конверсия утренних vs вечерних заявок", "json": {"report_title": "Time-based Conversion", "main_metric": {"label": "Time Impact", "value": {"operation": "avg", "entity": "time_based_conversion"}}}},
{"query": "конверсия мобильных vs десктоп заявок", "json": {"report_title": "Device Conversion", "main_metric": {"label": "Device Impact", "value": {"operation": "avg", "entity": "device_conversion"}}}},
{"query": "конверсия по длине резюме", "json": {"report_title": "Resume Length Conversion", "main_metric": {"label": "Length Impact", "value": {"operation": "avg", "entity": "resume_length_conversion"}}}},
{"query": "конверсия с фото vs без фото", "json": {"report_title": "Photo Impact Conversion", "main_metric": {"label": "Photo Impact", "value": {"operation": "avg", "entity": "photo_conversion"}}}},
{"query": "конверсия по уровню зарплаты", "json": {"report_title": "Salary Level Conversion", "main_metric": {"label": "Salary Impact", "value": {"operation": "avg", "entity": "salary_conversion"}}, "chart": {"graph_description": "Conversion by salary range", "chart_type": "bar", "x_axis_name": "Salary Range", "y_axis_name": "Conversion %", "x_axis": {"operation": "field", "field": "salary_range"}, "y_axis": {"operation": "avg", "entity": "salary_conversion", "group_by": {"field": "salary_range"}}}}},
{"query": "конверсия референсов", "json": {"report_title": "Reference Conversion", "main_metric": {"label": "Reference Impact", "value": {"operation": "avg", "entity": "reference_conversion"}}}},
{"query": "конверсия по опыту работы", "json": {"report_title": "Experience Conversion", "main_metric": {"label": "Experience Impact", "value": {"operation": "avg", "entity": "experience_conversion"}}, "chart": {"graph_description": "Conversion by years of experience", "chart_type": "line", "x_axis_name": "Years Experience", "y_axis_name": "Conversion %", "x_axis": {"operation": "field", "field": "years_experience"}, "y_axis": {"operation": "avg", "entity": "experience_conversion", "group_by": {"field": "experience_years"}}}}},
{"query": "конверсия по образованию", "json": {"report_title": "Education Conversion", "main_metric": {"label": "Education Impact", "value": {"operation": "avg", "entity": "education_conversion"}}}},
{"query": "конверсия горячих vs холодных лидов", "json": {"report_title": "Hot vs Cold Lead Conversion", "main_metric": {"label": "Lead Temperature", "value": {"operation": "avg", "entity": "lead_temperature_conversion"}}}},
{"query": "конверсия по отраслям", "json": {"report_title": "Industry Conversion", "main_metric": {"label": "Industry Impact", "value": {"operation": "avg", "entity": "industry_conversion"}}, "chart": {"graph_description": "Conversion by industry background", "chart_type": "bar", "x_axis_name": "Industry", "y_axis_name": "Conversion %", "x_axis": {"operation": "field", "field": "industry_name"}, "y_axis": {"operation": "avg", "entity": "industry_conversion", "group_by": {"field": "industry_name"}}}}},
{"query": "конверсия технических vs нетехнических ролей", "json": {"report_title": "Tech vs Non-Tech Conversion", "main_metric": {"label": "Role Type Impact", "value": {"operation": "avg", "entity": "role_type_conversion"}}}},
{"query": "конверсия стартапов vs корпораций", "json": {"report_title": "Startup vs Corporate Conversion", "main_metric": {"label": "Company Type", "value": {"operation": "avg", "entity": "company_type_conversion"}}}},
{"query": "конверсия удаленных vs офисных позиций", "json": {"report_title": "Remote vs Office Conversion", "main_metric": {"label": "Work Format Impact", "value": {"operation": "avg", "entity": "work_format_conversion"}}}},
{"query": "конверсия полной vs частичной занятости", "json": {"report_title": "Full vs Part Time Conversion", "main_metric": {"label": "Employment Type", "value": {"operation": "avg", "entity": "employment_type_conversion"}}}},
{"query": "прогноз конверсии", "json": {"report_title": "Conversion Forecast", "main_metric": {"label": "Predicted Rate", "value": {"operation": "avg", "entity": "conversion_forecast"}}}},

# ==========================================
# CATEGORY 5: STATUS & PIPELINE ANALYSIS (111-140)
# ==========================================

{"query": "распределение кандидатов по статусам", "json": {"report_title": "Candidate Status Distribution", "main_metric": {"label": "Total Active Candidates", "value": {"operation": "count", "entity": "applicants_by_status"}}, "chart": {"graph_description": "Current candidates across pipeline stages", "chart_type": "bar", "x_axis_name": "Status", "y_axis_name": "Candidates", "x_axis": {"operation": "field", "field": "status_name"}, "y_axis": {"operation": "count", "entity": "applicants_by_status", "group_by": {"field": "status_name"}}}}},
{"query": "кандидаты в статусе Новые", "json": {"report_title": "New Candidates", "main_metric": {"label": "New Status Candidates", "value": {"operation": "count", "entity": "applicants_by_status", "filter": {"field": "status_name", "op": "eq", "value": "Новые"}}}}},
{"query": "кандидаты на интервью", "json": {"report_title": "Interview Stage Candidates", "main_metric": {"label": "Interview Candidates", "value": {"operation": "count", "entity": "applicants_by_status", "filter": {"field": "status_name", "op": "eq", "value": "Интервью"}}}}},
{"query": "отказы по этапам воронки", "json": {"report_title": "Rejections by Pipeline Stage", "main_metric": {"label": "Total Rejections", "value": {"operation": "sum", "entity": "rejections_by_stage"}}, "chart": {"graph_description": "Rejection distribution across pipeline stages", "chart_type": "bar", "x_axis_name": "Pipeline Stage", "y_axis_name": "Rejections", "x_axis": {"operation": "field", "field": "stage_name"}, "y_axis": {"operation": "count", "entity": "rejections_by_stage", "group_by": {"field": "stage_name"}}}}},
{"query": "статусы по типам", "json": {"report_title": "Statuses by Type", "main_metric": {"label": "Total Status Types", "value": {"operation": "count", "entity": "statuses_by_type"}}, "chart": {"graph_description": "Status distribution by type", "chart_type": "pie", "x_axis_name": "Status Type", "y_axis_name": "Count", "x_axis": {"operation": "field", "field": "status_type"}, "y_axis": {"operation": "count", "entity": "statuses_by_type", "group_by": {"field": "status_type"}}}}},
{"query": "группы статусов и их размеры", "json": {"report_title": "Status Groups Overview", "main_metric": {"label": "Total Groups", "value": {"operation": "count", "entity": "status_groups"}}, "chart": {"graph_description": "Status groups with their stage counts", "chart_type": "bar", "x_axis_name": "Status Group", "y_axis_name": "Number of Stages", "x_axis": {"operation": "field", "field": "group_name"}, "y_axis": {"operation": "count", "entity": "status_groups", "group_by": {"field": "group_name"}}}}},
{"query": "узкие места в воронке", "json": {"report_title": "Pipeline Bottlenecks", "main_metric": {"label": "Bottleneck Score", "value": {"operation": "max", "entity": "pipeline_bottlenecks"}}, "chart": {"graph_description": "Stages with highest candidate accumulation", "chart_type": "bar", "x_axis_name": "Stage", "y_axis_name": "Accumulation Score", "x_axis": {"operation": "field", "field": "stage_name"}, "y_axis": {"operation": "count", "entity": "pipeline_bottlenecks", "group_by": {"field": "stage_name"}}}}},
{"query": "время в каждом статусе", "json": {"report_title": "Time in Each Status", "main_metric": {"label": "Average Time", "value": {"operation": "avg", "entity": "time_in_status"}}, "chart": {"graph_description": "Average days spent in each status", "chart_type": "bar", "x_axis_name": "Status", "y_axis_name": "Days", "x_axis": {"operation": "field", "field": "status_name"}, "y_axis": {"operation": "avg", "entity": "time_in_status", "group_by": {"field": "status_name"}}}}},
{"query": "переходы между статусами", "json": {"report_title": "Status Transitions", "main_metric": {"label": "Total Transitions", "value": {"operation": "sum", "entity": "status_transitions"}}, "chart": {"graph_description": "Most common status transitions", "chart_type": "bar", "x_axis_name": "Transition", "y_axis_name": "Count", "x_axis": {"operation": "field", "field": "transition_name"}, "y_axis": {"operation": "count", "entity": "status_transitions", "group_by": {"field": "transition_name"}}}}},
{"query": "пропущенные этапы", "json": {"report_title": "Skipped Stages", "main_metric": {"label": "Skipped Count", "value": {"operation": "sum", "entity": "skipped_stages"}}}},
{"query": "возвраты в предыдущие статусы", "json": {"report_title": "Backward Status Moves", "main_metric": {"label": "Backward Moves", "value": {"operation": "sum", "entity": "backward_moves"}}}},
{"query": "финальные статусы", "json": {"report_title": "Final Statuses", "main_metric": {"label": "Final Status Distribution", "value": {"operation": "count", "entity": "final_statuses"}}, "chart": {"graph_description": "Where candidates end up", "chart_type": "pie", "x_axis_name": "Final Status", "y_axis_name": "Count", "x_axis": {"operation": "field", "field": "final_status"}, "y_axis": {"operation": "count", "entity": "final_statuses", "group_by": {"field": "final_status"}}}}},
{"query": "активность по статусам", "json": {"report_title": "Activity by Status", "main_metric": {"label": "Status Activity", "value": {"operation": "sum", "entity": "status_activity"}}, "chart": {"graph_description": "Activity level in each status", "chart_type": "bar", "x_axis_name": "Status", "y_axis_name": "Activity Score", "x_axis": {"operation": "field", "field": "status_name"}, "y_axis": {"operation": "sum", "entity": "status_activity", "group_by": {"field": "status_name"}}}}},
{"query": "статусы с наибольшим временем", "json": {"report_title": "Longest Duration Statuses", "main_metric": {"label": "Max Duration", "value": {"operation": "max", "entity": "status_duration"}}}},
{"query": "статусы с наименьшим временем", "json": {"report_title": "Shortest Duration Statuses", "main_metric": {"label": "Min Duration", "value": {"operation": "min", "entity": "status_duration"}}}},
{"query": "самые популярные первые статусы", "json": {"report_title": "Most Common Entry Points", "main_metric": {"label": "Entry Point", "value": {"operation": "max", "entity": "entry_statuses"}}}},
{"query": "пути через воронку", "json": {"report_title": "Funnel Paths", "main_metric": {"label": "Path Diversity", "value": {"operation": "count", "entity": "funnel_paths"}}}},
{"query": "статусы-ловушки", "json": {"report_title": "Status Traps", "main_metric": {"label": "Trap Score", "value": {"operation": "max", "entity": "status_traps"}}}},
{"query": "эффективность статусов", "json": {"report_title": "Status Effectiveness", "main_metric": {"label": "Effectiveness Score", "value": {"operation": "avg", "entity": "status_effectiveness"}}, "chart": {"graph_description": "How effective each status is", "chart_type": "bar", "x_axis_name": "Status", "y_axis_name": "Effectiveness", "x_axis": {"operation": "field", "field": "status_name"}, "y_axis": {"operation": "avg", "entity": "status_effectiveness", "group_by": {"field": "status_name"}}}}},
{"query": "скорость прохождения воронки", "json": {"report_title": "Funnel Speed", "main_metric": {"label": "Average Speed", "value": {"operation": "avg", "entity": "funnel_speed"}}}},
{"query": "параллельные процессы", "json": {"report_title": "Parallel Processes", "main_metric": {"label": "Parallel Count", "value": {"operation": "count", "entity": "parallel_processes"}}}},
{"query": "точки принятия решений", "json": {"report_title": "Decision Points", "main_metric": {"label": "Decision Count", "value": {"operation": "count", "entity": "decision_points"}}}},
{"query": "автоматические vs ручные переходы", "json": {"report_title": "Auto vs Manual Transitions", "main_metric": {"label": "Automation Level", "value": {"operation": "avg", "entity": "transition_automation"}}}},
{"query": "качество данных по статусам", "json": {"report_title": "Status Data Quality", "main_metric": {"label": "Data Quality Score", "value": {"operation": "avg", "entity": "status_data_quality"}}}},
{"query": "консистентность процессов", "json": {"report_title": "Process Consistency", "main_metric": {"label": "Consistency Index", "value": {"operation": "avg", "entity": "process_consistency"}}}},
{"query": "отклонения от стандартного пути", "json": {"report_title": "Process Deviations", "main_metric": {"label": "Deviation Count", "value": {"operation": "sum", "entity": "process_deviations"}}}},
{"query": "оптимизация воронки", "json": {"report_title": "Funnel Optimization", "main_metric": {"label": "Optimization Score", "value": {"operation": "avg", "entity": "funnel_optimization"}}}},
{"query": "влияние внешних факторов", "json": {"report_title": "External Factors Impact", "main_metric": {"label": "External Impact", "value": {"operation": "avg", "entity": "external_factors"}}}},
{"query": "сегментация кандидатов", "json": {"report_title": "Candidate Segmentation", "main_metric": {"label": "Segment Count", "value": {"operation": "count", "entity": "candidate_segments"}}}},
{"query": "прогнозирование переходов", "json": {"report_title": "Transition Forecasting", "main_metric": {"label": "Forecast Accuracy", "value": {"operation": "avg", "entity": "transition_forecast"}}}},

# ==========================================
# CATEGORY 6: VACANCY ANALYSIS (141-170)
# ==========================================

{"query": "вакансии по состоянию", "json": {"report_title": "Vacancies by State", "main_metric": {"label": "Total Vacancies", "value": {"operation": "count", "entity": "vacancies_by_state"}}, "chart": {"graph_description": "Vacancy distribution by state", "chart_type": "pie", "x_axis_name": "State", "y_axis_name": "Count", "x_axis": {"operation": "field", "field": "state"}, "y_axis": {"operation": "count", "entity": "vacancies_by_state", "group_by": {"field": "state"}}}}},
{"query": "вакансии по приоритету", "json": {"report_title": "Vacancies by Priority", "main_metric": {"label": "Total Vacancies", "value": {"operation": "count", "entity": "vacancies_by_priority"}}, "chart": {"graph_description": "Vacancy distribution by priority level", "chart_type": "bar", "x_axis_name": "Priority", "y_axis_name": "Count", "x_axis": {"operation": "field", "field": "priority"}, "y_axis": {"operation": "count", "entity": "vacancies_by_priority", "group_by": {"field": "priority"}}}}},
{"query": "высокоприоритетные открытые вакансии", "json": {"report_title": "High Priority Open Vacancies", "main_metric": {"label": "High Priority Open", "value": {"operation": "count", "entity": "vacancies_all", "filter": [{"field": "state", "op": "eq", "value": "OPEN"}, {"field": "priority", "op": "eq", "value": "high"}]}}}},
{"query": "недавно закрытые вакансии", "json": {"report_title": "Recently Closed Vacancies", "main_metric": {"label": "Recently Closed", "value": {"operation": "count", "entity": "vacancies_all", "filter": [{"field": "state", "op": "eq", "value": "CLOSED"}, {"field": "updated", "op": "gte", "value": "2025-05-19T00:00:00"}]}}}},
{"query": "вакансии по отделам", "json": {"report_title": "Vacancies by Department", "main_metric": {"label": "Department Distribution", "value": {"operation": "count", "entity": "vacancies_by_department"}}, "chart": {"graph_description": "Vacancy distribution by department", "chart_type": "bar", "x_axis_name": "Department", "y_axis_name": "Vacancies", "x_axis": {"operation": "field", "field": "department_name"}, "y_axis": {"operation": "count", "entity": "vacancies_by_department", "group_by": {"field": "department_name"}}}}},
{"query": "возраст открытых вакансий", "json": {"report_title": "Open Vacancy Age", "main_metric": {"label": "Average Age (Days)", "value": {"operation": "avg", "entity": "vacancy_age"}}, "chart": {"graph_description": "Age distribution of open vacancies", "chart_type": "bar", "x_axis_name": "Age Range", "y_axis_name": "Count", "x_axis": {"operation": "field", "field": "age_range"}, "y_axis": {"operation": "count", "entity": "vacancy_age", "group_by": {"field": "age_range"}}}}},
{"query": "бюджет вакансий", "json": {"report_title": "Vacancy Budget Analysis", "main_metric": {"label": "Average Budget", "value": {"operation": "avg", "entity": "vacancy_budget"}}, "chart": {"graph_description": "Budget distribution across vacancies", "chart_type": "bar", "x_axis_name": "Budget Range", "y_axis_name": "Count", "x_axis": {"operation": "field", "field": "budget_range"}, "y_axis": {"operation": "count", "entity": "vacancy_budget", "group_by": {"field": "budget_range"}}}}},
{"query": "популярные позиции", "json": {"report_title": "Popular Positions", "main_metric": {"label": "Most Common Position", "value": {"operation": "max", "entity": "popular_positions"}}, "chart": {"graph_description": "Most frequently posted positions", "chart_type": "bar", "x_axis_name": "Position", "y_axis_name": "Count", "x_axis": {"operation": "field", "field": "position_name"}, "y_axis": {"operation": "count", "entity": "popular_positions", "group_by": {"field": "position_name"}}}}},
{"query": "требования к вакансиям", "json": {"report_title": "Vacancy Requirements", "main_metric": {"label": "Requirement Complexity", "value": {"operation": "avg", "entity": "vacancy_requirements"}}}},
{"query": "географическое распределение", "json": {"report_title": "Geographic Distribution", "main_metric": {"label": "Regional Spread", "value": {"operation": "count", "entity": "vacancies_by_region"}}, "chart": {"graph_description": "Vacancies by region", "chart_type": "pie", "x_axis_name": "Region", "y_axis_name": "Count", "x_axis": {"operation": "field", "field": "region_name"}, "y_axis": {"operation": "count", "entity": "vacancies_by_region", "group_by": {"field": "region_name"}}}}},
{"query": "удаленные vs офисные позиции", "json": {"report_title": "Remote vs Office Positions", "main_metric": {"label": "Work Format Split", "value": {"operation": "count", "entity": "work_format_split"}}, "chart": {"graph_description": "Distribution by work format", "chart_type": "pie", "x_axis_name": "Work Format", "y_axis_name": "Count", "x_axis": {"operation": "field", "field": "work_format"}, "y_axis": {"operation": "count", "entity": "work_format_split", "group_by": {"field": "work_format"}}}}},
{"query": "уровни позиций", "json": {"report_title": "Position Levels", "main_metric": {"label": "Level Distribution", "value": {"operation": "count", "entity": "position_levels"}}, "chart": {"graph_description": "Distribution by seniority level", "chart_type": "bar", "x_axis_name": "Level", "y_axis_name": "Count", "x_axis": {"operation": "field", "field": "seniority_level"}, "y_axis": {"operation": "count", "entity": "position_levels", "group_by": {"field": "seniority_level"}}}}},
{"query": "технические vs нетехнические роли", "json": {"report_title": "Tech vs Non-Tech Roles", "main_metric": {"label": "Role Type Distribution", "value": {"operation": "count", "entity": "role_types"}}, "chart": {"graph_description": "Technical vs non-technical roles", "chart_type": "pie", "x_axis_name": "Role Type", "y_axis_name": "Count", "x_axis": {"operation": "field", "field": "role_type"}, "y_axis": {"operation": "count", "entity": "role_types", "group_by": {"field": "role_type"}}}}},
{"query": "срочные вакансии", "json": {"report_title": "Urgent Vacancies", "main_metric": {"label": "Urgent Count", "value": {"operation": "count", "entity": "urgent_vacancies"}}}},
{"query": "вакансии с множественным наймом", "json": {"report_title": "Multiple Hire Vacancies", "main_metric": {"label": "Multiple Hire Count", "value": {"operation": "count", "entity": "multiple_hire_vacancies"}}}},
{"query": "квоты найма", "json": {"report_title": "Hiring Quotas", "main_metric": {"label": "Total Quota", "value": {"operation": "sum", "entity": "hiring_quotas"}}, "chart": {"graph_description": "Hiring quotas by department", "chart_type": "bar", "x_axis_name": "Department", "y_axis_name": "Quota", "x_axis": {"operation": "field", "field": "department_name"}, "y_axis": {"operation": "sum", "entity": "hiring_quotas", "group_by": {"field": "department_name"}}}}},
{"query": "прогресс по квотам", "json": {"report_title": "Quota Progress", "main_metric": {"label": "Quota Completion %", "value": {"operation": "avg", "entity": "quota_progress"}}}},
{"query": "вакансии без кандидатов", "json": {"report_title": "Vacancies Without Candidates", "main_metric": {"label": "Empty Vacancies", "value": {"operation": "count", "entity": "empty_vacancies"}}}},
{"query": "перегруженные вакансии", "json": {"report_title": "Overloaded Vacancies", "main_metric": {"label": "Overloaded Count", "value": {"operation": "count", "entity": "overloaded_vacancies"}}}},
{"query": "сезонные вакансии", "json": {"report_title": "Seasonal Vacancies", "main_metric": {"label": "Seasonal Pattern", "value": {"operation": "count", "entity": "seasonal_vacancies"}}, "chart": {"graph_description": "Vacancy posting by season", "chart_type": "line", "x_axis_name": "Month", "y_axis_name": "Posted", "x_axis": {"operation": "date_trunc", "field": "created"}, "y_axis": {"operation": "count", "entity": "seasonal_vacancies", "group_by": {"field": "month"}}}}},
{"query": "конкурентность позиций", "json": {"report_title": "Position Competitiveness", "main_metric": {"label": "Competition Index", "value": {"operation": "avg", "entity": "position_competitiveness"}}}},
{"query": "скорость заполнения", "json": {"report_title": "Fill Speed", "main_metric": {"label": "Average Fill Time", "value": {"operation": "avg", "entity": "fill_speed"}}, "chart": {"graph_description": "Time to fill by position type", "chart_type": "bar", "x_axis_name": "Position Type", "y_axis_name": "Days", "x_axis": {"operation": "field", "field": "position_type"}, "y_axis": {"operation": "avg", "entity": "fill_speed", "group_by": {"field": "position_type"}}}}},
{"query": "сложность позиций", "json": {"report_title": "Position Complexity", "main_metric": {"label": "Complexity Score", "value": {"operation": "avg", "entity": "position_complexity"}}}},
{"query": "рыночная ситуация", "json": {"report_title": "Market Conditions", "main_metric": {"label": "Market Index", "value": {"operation": "avg", "entity": "market_conditions"}}}},
{"query": "тренды в требованиях", "json": {"report_title": "Requirement Trends", "main_metric": {"label": "Trend Direction", "value": {"operation": "avg", "entity": "requirement_trends"}}}},
{"query": "качество описаний вакансий", "json": {"report_title": "Job Description Quality", "main_metric": {"label": "Quality Score", "value": {"operation": "avg", "entity": "description_quality"}}}},
{"query": "привлекательность предложений", "json": {"report_title": "Offer Attractiveness", "main_metric": {"label": "Attractiveness Score", "value": {"operation": "avg", "entity": "offer_attractiveness"}}}},
{"query": "соответствие рынку", "json": {"report_title": "Market Alignment", "main_metric": {"label": "Alignment Score", "value": {"operation": "avg", "entity": "market_alignment"}}}},
{"query": "инновационность ролей", "json": {"report_title": "Role Innovation", "main_metric": {"label": "Innovation Index", "value": {"operation": "avg", "entity": "role_innovation"}}}},
{"query": "стабильность команд", "json": {"report_title": "Team Stability", "main_metric": {"label": "Stability Index", "value": {"operation": "avg", "entity": "team_stability"}}}},

# ==========================================
# CATEGORY 7: SOURCE & ORIGIN ANALYSIS (171-190)
# ==========================================

{"query": "кандидаты по источникам", "json": {"report_title": "Candidates by Source", "main_metric": {"label": "Total Sources", "value": {"operation": "count", "entity": "applicants_by_source"}}, "chart": {"graph_description": "Candidate distribution by source", "chart_type": "bar", "x_axis_name": "Source", "y_axis_name": "Candidates", "x_axis": {"operation": "field", "field": "source_name"}, "y_axis": {"operation": "count", "entity": "applicants_by_source", "group_by": {"field": "source_name"}}}}},
{"query": "отказы по причинам", "json": {"report_title": "Rejections by Reason", "main_metric": {"label": "Total Rejection Reasons", "value": {"operation": "count", "entity": "rejections_by_reason"}}, "chart": {"graph_description": "Rejection distribution by reason", "chart_type": "bar", "x_axis_name": "Rejection Reason", "y_axis_name": "Count", "x_axis": {"operation": "field", "field": "reason_name"}, "y_axis": {"operation": "count", "entity": "rejections_by_reason", "group_by": {"field": "reason_name"}}}}},
{"query": "кандидаты из LinkedIn", "json": {"report_title": "LinkedIn Candidates", "main_metric": {"label": "LinkedIn Sourced", "value": {"operation": "count", "entity": "applicants_by_source", "filter": {"field": "source_name", "op": "eq", "value": "LinkedIn"}}}}},
{"query": "внутренние рекомендации", "json": {"report_title": "Internal Referrals", "main_metric": {"label": "Referral Candidates", "value": {"operation": "count", "entity": "applicants_by_source", "filter": {"field": "source_name", "op": "eq", "value": "Referral"}}}}},
{"query": "эффективность источников найма", "json": {"report_title": "Source Effectiveness", "main_metric": {"label": "Best Source", "value": {"operation": "max", "entity": "applicants_by_source"}}, "chart": {"graph_description": "Candidate volume by recruitment source", "chart_type": "pie", "x_axis_name": "Source", "y_axis_name": "Candidates", "x_axis": {"operation": "field", "field": "source_name"}, "y_axis": {"operation": "count", "entity": "applicants_by_source", "group_by": {"field": "source_name"}}}}},
{"query": "качество источников", "json": {"report_title": "Source Quality", "main_metric": {"label": "Quality Index", "value": {"operation": "avg", "entity": "source_quality"}}, "chart": {"graph_description": "Quality score by source", "chart_type": "bar", "x_axis_name": "Source", "y_axis_name": "Quality Score", "x_axis": {"operation": "field", "field": "source_name"}, "y_axis": {"operation": "avg", "entity": "source_quality", "group_by": {"field": "source_name"}}}}},
{"query": "стоимость привлечения", "json": {"report_title": "Cost per Acquisition", "main_metric": {"label": "Average CPA", "value": {"operation": "avg", "entity": "cost_per_acquisition"}}, "chart": {"graph_description": "Cost per candidate by source", "chart_type": "bar", "x_axis_name": "Source", "y_axis_name": "Cost", "x_axis": {"operation": "field", "field": "source_name"}, "y_axis": {"operation": "avg", "entity": "cost_per_acquisition", "group_by": {"field": "source_name"}}}}},
{"query": "ROI источников", "json": {"report_title": "Source ROI", "main_metric": {"label": "Best ROI", "value": {"operation": "max", "entity": "source_roi"}}, "chart": {"graph_description": "Return on investment by source", "chart_type": "bar", "x_axis_name": "Source", "y_axis_name": "ROI %", "x_axis": {"operation": "field", "field": "source_name"}, "y_axis": {"operation": "avg", "entity": "source_roi", "group_by": {"field": "source_name"}}}}},
{"query": "социальные сети vs традиционные", "json": {"report_title": "Social vs Traditional Sources", "main_metric": {"label": "Channel Distribution", "value": {"operation": "count", "entity": "channel_distribution"}}, "chart": {"graph_description": "Modern vs traditional recruitment channels", "chart_type": "pie", "x_axis_name": "Channel Type", "y_axis_name": "Candidates", "x_axis": {"operation": "field", "field": "channel_type"}, "y_axis": {"operation": "count", "entity": "channel_distribution", "group_by": {"field": "channel_type"}}}}},
{"query": "органический vs платный трафик", "json": {"report_title": "Organic vs Paid Traffic", "main_metric": {"label": "Traffic Split", "value": {"operation": "count", "entity": "traffic_sources"}}, "chart": {"graph_description": "Organic vs paid candidate sources", "chart_type": "pie", "x_axis_name": "Traffic Type", "y_axis_name": "Candidates", "x_axis": {"operation": "field", "field": "traffic_type"}, "y_axis": {"operation": "count", "entity": "traffic_sources", "group_by": {"field": "traffic_type"}}}}},
{"query": "мобильные vs десктоп источники", "json": {"report_title": "Mobile vs Desktop Sources", "main_metric": {"label": "Device Distribution", "value": {"operation": "count", "entity": "device_sources"}}, "chart": {"graph_description": "Application source by device type", "chart_type": "pie", "x_axis_name": "Device", "y_axis_name": "Applications", "x_axis": {"operation": "field", "field": "device_type"}, "y_axis": {"operation": "count", "entity": "device_sources", "group_by": {"field": "device_type"}}}}},
{"query": "географические источники", "json": {"report_title": "Geographic Sources", "main_metric": {"label": "Geographic Diversity", "value": {"operation": "count", "entity": "geographic_sources"}}, "chart": {"graph_description": "Candidate sources by geography", "chart_type": "bar", "x_axis_name": "Region", "y_axis_name": "Candidates", "x_axis": {"operation": "field", "field": "region_name"}, "y_axis": {"operation": "count", "entity": "geographic_sources", "group_by": {"field": "region_name"}}}}},
{"query": "новые vs проверенные источники", "json": {"report_title": "New vs Proven Sources", "main_metric": {"label": "Source Maturity", "value": {"operation": "avg", "entity": "source_maturity"}}}},
{"query": "партнерские источники", "json": {"report_title": "Partner Sources", "main_metric": {"label": "Partner Performance", "value": {"operation": "avg", "entity": "partner_sources"}}, "chart": {"graph_description": "Performance of partner channels", "chart_type": "bar", "x_axis_name": "Partner", "y_axis_name": "Performance", "x_axis": {"operation": "field", "field": "partner_name"}, "y_axis": {"operation": "avg", "entity": "partner_sources", "group_by": {"field": "partner_name"}}}}},
{"query": "сезонность источников", "json": {"report_title": "Source Seasonality", "main_metric": {"label": "Seasonal Variation", "value": {"operation": "avg", "entity": "source_seasonality"}}, "chart": {"graph_description": "Source performance by season", "chart_type": "line", "x_axis_name": "Month", "y_axis_name": "Performance", "x_axis": {"operation": "date_trunc", "field": "created"}, "y_axis": {"operation": "avg", "entity": "source_seasonality", "group_by": {"field": "month"}}}}},
{"query": "нишевые источники", "json": {"report_title": "Niche Sources", "main_metric": {"label": "Niche Performance", "value": {"operation": "avg", "entity": "niche_sources"}}}},
{"query": "международные источники", "json": {"report_title": "International Sources", "main_metric": {"label": "International Volume", "value": {"operation": "count", "entity": "international_sources"}}}},
{"query": "университетские связи", "json": {"report_title": "University Connections", "main_metric": {"label": "University Candidates", "value": {"operation": "count", "entity": "university_sources"}}, "chart": {"graph_description": "Candidates by university", "chart_type": "bar", "x_axis_name": "University", "y_axis_name": "Candidates", "x_axis": {"operation": "field", "field": "university_name"}, "y_axis": {"operation": "count", "entity": "university_sources", "group_by": {"field": "university_name"}}}}},
{"query": "конференции и события", "json": {"report_title": "Events and Conferences", "main_metric": {"label": "Event ROI", "value": {"operation": "avg", "entity": "event_sources"}}}},
{"query": "employee advocacy", "json": {"report_title": "Employee Advocacy", "main_metric": {"label": "Advocacy Impact", "value": {"operation": "avg", "entity": "employee_advocacy"}}}},

# ==========================================
# CATEGORY 8: COMPLEX MULTI-FILTER QUERIES (191-200)
# ==========================================

{"query": "кандидаты у Анастасии на высокоприоритетных вакансиях", "json": {"report_title": "Анастасия High Priority Candidates", "main_metric": {"label": "High Priority Candidates", "value": {"operation": "count", "entity": "applicants_by_recruiter", "filter": [{"field": "recruiter_name", "op": "eq", "value": "Анастасия Богач"}, {"field": "vacancy_priority", "op": "eq", "value": "high"}]}}}},
{"query": "недавние найма от топ рекрутеров", "json": {"report_title": "Recent Hires by Top Recruiters", "main_metric": {"label": "Recent Top Recruiter Hires", "value": {"operation": "count", "entity": "applicants_hired", "filter": [{"field": "recruiter_name", "op": "in", "value": ["Анастасия Богач", "Михаил Танский", "Виталий Глибин"]}, {"field": "hired_date", "op": "gte", "value": "2025-03-20T00:00:00"}]}}}},
{"query": "активные вакансии с высокой конверсией созданные в этом году", "json": {"report_title": "High Converting Active Vacancies This Year", "main_metric": {"label": "High Converting Active", "value": {"operation": "count", "entity": "vacancy_conversion_rates", "filter": [{"field": "vacancy_state", "op": "eq", "value": "OPEN"}, {"field": "conversion_rate", "op": "gte", "value": 10}, {"field": "created", "op": "gte", "value": "2024-06-18T00:00:00"}]}}}},
{"query": "кандидаты из LinkedIn на IT вакансиях за последние 3 месяца", "json": {"report_title": "LinkedIn IT Candidates Last 3 Months", "main_metric": {"label": "LinkedIn IT Candidates", "value": {"operation": "count", "entity": "applicants_by_source", "filter": [{"field": "source_name", "op": "eq", "value": "LinkedIn"}, {"field": "vacancy_position", "op": "icontains", "value": "Developer"}, {"field": "created", "op": "gte", "value": "2025-03-20T00:00:00"}]}}}},
{"query": "конверсия топ 3 рекрутеров в найм за год", "json": {"report_title": "Top 3 Recruiters Year Conversion", "main_metric": {"label": "Top Recruiters Conversion", "value": {"operation": "avg", "entity": "vacancy_conversion_rates", "filter": [{"field": "recruiter_name", "op": "in", "value": ["Анастасия Богач", "Михаил Танский", "Виталий Глибин"]}, {"field": "created", "op": "gte", "value": "2024-06-18T00:00:00"}]}}, "chart": {"graph_description": "Conversion rates of top recruiters this year", "chart_type": "bar", "x_axis_name": "Recruiter", "y_axis_name": "Conversion Rate (%)", "x_axis": {"operation": "field", "field": "recruiter_name"}, "y_axis": {"operation": "avg", "entity": "vacancy_conversion_rates", "filter": [{"field": "recruiter_name", "op": "in", "value": ["Анастасия Богач", "Михаил Танский", "Виталий Глибин"]}, {"field": "created", "op": "gte", "value": "2024-06-18T00:00:00"}], "group_by": {"field": "recruiter_name"}}}}},
{"query": "активные кандидаты по статусам на открытых нормальных приоритетах", "json": {"report_title": "Active Candidates Normal Priority Open Vacancies", "main_metric": {"label": "Normal Priority Active Candidates", "value": {"operation": "count", "entity": "applicants_by_status", "filter": [{"field": "vacancy_state", "op": "eq", "value": "OPEN"}, {"field": "vacancy_priority", "op": "eq", "value": "normal"}, {"field": "status_type", "op": "eq", "value": "user"}]}}, "chart": {"graph_description": "Status distribution for normal priority open vacancies", "chart_type": "pie", "x_axis_name": "Status", "y_axis_name": "Candidates", "x_axis": {"operation": "field", "field": "status_name"}, "y_axis": {"operation": "count", "entity": "applicants_by_status", "filter": [{"field": "vacancy_state", "op": "eq", "value": "OPEN"}, {"field": "vacancy_priority", "op": "eq", "value": "normal"}], "group_by": {"field": "status_name"}}}}},
{"query": "внутренние рекомендации с высокой конверсией созданные в этом году", "json": {"report_title": "High Converting Internal Referrals This Year", "main_metric": {"label": "High Converting Referrals", "value": {"operation": "count", "entity": "applicants_by_source", "filter": [{"field": "source_name", "op": "eq", "value": "Referral"}, {"field": "conversion_rate", "op": "gte", "value": 15}, {"field": "created", "op": "gte", "value": "2024-06-18T00:00:00"}]}}}},
{"query": "закрытые вакансии с успешным наймом за полгода", "json": {"report_title": "Successfully Closed Vacancies 6 Months", "main_metric": {"label": "Successfully Closed", "value": {"operation": "count", "entity": "vacancies_all", "filter": [{"field": "state", "op": "eq", "value": "CLOSED"}, {"field": "hired_count", "op": "gte", "value": 1}, {"field": "updated", "op": "gte", "value": "2024-12-20T00:00:00"}]}}}},
{"query": "комплексная аналитика эффективности найма", "json": {"report_title": "Comprehensive Hiring Efficiency Analysis", "main_metric": {"label": "Overall Efficiency Score", "value": {"operation": "avg", "entity": "vacancy_conversion_summary"}}, "secondary_metrics": [{"label": "Total Conversions", "value": {"operation": "count", "entity": "vacancy_conversion_rates"}}, {"label": "Top Performer Rate", "value": {"operation": "max", "entity": "vacancy_conversion_rates"}}], "chart": {"graph_description": "Comprehensive hiring efficiency across all metrics", "chart_type": "scatter", "x_axis_name": "Applicants per Vacancy", "y_axis_name": "Conversion Rate (%)", "x_axis": {"operation": "field", "field": "applicant_count"}, "y_axis": {"operation": "field", "field": "conversion_rate", "entity": "vacancy_conversion_summary"}}}},
{"query": "финальная комплексная HR метрика по всем направлениям деятельности", "json": {"report_title": "Ultimate HR Performance Dashboard", "main_metric": {"label": "Overall HR Performance Index", "value": {"operation": "avg", "entity": "vacancy_conversion_summary"}}, "secondary_metrics": [{"label": "Total Active Pipeline", "value": {"operation": "count", "entity": "applicants_by_status"}}, {"label": "Recruiter Efficiency", "value": {"operation": "avg", "entity": "actions_by_recruiter"}}, {"label": "Source Diversity", "value": {"operation": "count", "entity": "applicants_by_source"}}], "chart": {"graph_description": "Complete HR performance overview across all KPIs", "chart_type": "table", "x_axis_name": "Metric Category", "y_axis_name": "Performance Value", "x_axis": {"operation": "field", "field": "metric_category"}, "y_axis": {"operation": "avg", "entity": "vacancy_conversion_summary", "group_by": {"field": "performance_index"}}}}}

]

def get_example_by_category(category_name: str):
    """Get examples filtered by category."""
    categories = {
        "basic_counts": HR_ANALYTICS_EXAMPLES[0:25],
        "time_based": HR_ANALYTICS_EXAMPLES[25:50], 
        "recruiter_performance": HR_ANALYTICS_EXAMPLES[50:80],
        "conversion_metrics": HR_ANALYTICS_EXAMPLES[80:110],
        "status_pipeline": HR_ANALYTICS_EXAMPLES[110:140],
        "vacancy_analysis": HR_ANALYTICS_EXAMPLES[140:170],
        "source_analysis": HR_ANALYTICS_EXAMPLES[170:190],
        "complex_queries": HR_ANALYTICS_EXAMPLES[190:200]
    }
    return categories.get(category_name, [])

def get_random_examples(count: int = 10):
    """Get random selection of examples."""
    import random
    return random.sample(HR_ANALYTICS_EXAMPLES, min(count, len(HR_ANALYTICS_EXAMPLES)))

def get_examples_by_metric(metric_name: str):
    """Get examples that use a specific metric."""
    matching_examples = []
    for example in HR_ANALYTICS_EXAMPLES:
        json_data = example.get("json", {})
        main_metric = json_data.get("main_metric", {})
        entity = main_metric.get("value", {}).get("entity", "")
        if metric_name in entity:
            matching_examples.append(example)
    return matching_examples

def validate_examples():
    """Validate that all examples use correct systematic metric names."""
    systematic_metrics = {
        "applicants_all", "vacancies_all", "recruiters_all", "statuses_all",
        "applicants_by_status", "applicants_by_recruiter", "vacancies_by_state",
        "actions_by_recruiter", "moves_by_recruiter", "rejections_by_recruiter",
        "rejections_by_stage", "rejections_by_reason", "vacancy_conversion_rates",
        "vacancy_conversion_summary", "vacancy_conversion_by_status", "status_groups"
    }
    
    issues = []
    for i, example in enumerate(HR_ANALYTICS_EXAMPLES):
        json_data = example.get("json", {})
        main_metric = json_data.get("main_metric", {})
        entity = main_metric.get("value", {}).get("entity", "")
        
        # Check if using systematic naming
        is_systematic = any(metric in entity for metric in systematic_metrics)
        if not is_systematic and entity not in ["applicants", "vacancies", "recruiters", "vacancy_statuses"]:
            issues.append(f"Example {i+1}: '{entity}' is not a systematic metric")
    
    return issues

# Example usage and statistics
if __name__ == "__main__":
    print(f"Total examples: {len(HR_ANALYTICS_EXAMPLES)}")
    print(f"Categories: {list(get_example_by_category.__annotations__.keys()) if hasattr(get_example_by_category, '__annotations__') else 'basic_counts, time_based, recruiter_performance, conversion_metrics, status_pipeline, vacancy_analysis, source_analysis, complex_queries'}")
    
    # Show first example
    example = HR_ANALYTICS_EXAMPLES[0]
    print(f"\nSample query: {example['query']}")
    print(f"JSON structure: {example['json']}")
    
    # Validate examples
    validation_issues = validate_examples()
    if validation_issues:
        print(f"\nValidation issues found: {len(validation_issues)}")
        for issue in validation_issues[:5]:  # Show first 5
            print(f"  - {issue}")
    else:
        print("\nAll examples validated successfully!")
    
    # Show category statistics
    print(f"\nCategory breakdown:")
    categories = {
        "Basic Counts": len(get_example_by_category("basic_counts")),
        "Time-based": len(get_example_by_category("time_based")),
        "Recruiter Performance": len(get_example_by_category("recruiter_performance")),
        "Conversion Metrics": len(get_example_by_category("conversion_metrics")),
        "Status Pipeline": len(get_example_by_category("status_pipeline")),
        "Vacancy Analysis": len(get_example_by_category("vacancy_analysis")),
        "Source Analysis": len(get_example_by_category("source_analysis")),
        "Complex Queries": len(get_example_by_category("complex_queries"))
    }
    
    for category, count in categories.items():
        print(f"  {category}: {count} examples")